__author__ = 'Michael'

CLIENT_REGISTRY_KEY = 'client'

ROLE_APP_CLIENT = 'AppClient'
ROLE_BASIC_USER = 'BasicUser'

TOKEN_TEST_API = 'TEST_API'
TOKEN_READ_PROVIDERS = 'READ_PROVIDERS'
TOKEN_READ_GROUPS = 'READ_GROUPS'
TOKEN_READ_FORUM = 'READ_FORUM'
TOKEN_WRITE_FORUM = 'WRITE_FORUM'