application: kudos-app-646
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
#- url: /favicon\.ico
#  static_files: favicon.ico
#  upload: favicon\.ico

# Route API calls to the main application service
- url: /api/.*
  script: main.app

# Route APP calls to the static server
- url: /
  static_dir: static/

# TODO (michael) Route anything else to a 404 error
#- url: /.*
#  script: not_found.app

libraries:
- name: webapp2
  version: "2.5.2"
